# Generated by Django 2.1.5 on 2019-02-01 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 9, 11, 0, 546404), verbose_name='date published'),
        ),
    ]
